// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MiniProjects.Models;

public partial class User
{
    public int Id { get; set; }

    public string Names { get; set; }

    public string Passwords { get; set; }

    public DateTime CreatedDate { get; set; }
}